version: "3.9"

services:
  backend:
    build: ./backend
    container_name: api_backend
    ports:
      - "8000:8000"  
    networks:
      - attendance_network
    restart: always

  frontend:
    build: ./frontend
    container_name: UI_frontend
    ports:
      - "8501:8501"  
    depends_on:
      - backend  
    networks:
      - attendance_network
    restart: always

networks:
  attendance_network:
    driver: bridge
